AChallenge.WebUI/Controllers/RespondentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AChallenge.Business.Concrete;
using AChallenge.Models.Concrete;
using AChallenge.WebUI.Helpers.Auth;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AChallenge.WebUI.Controllers
{
    [AuthFilterRespondent]
    public class RespondentController : Controller
    {

        SurveyManager _surveyManager { get; set; }
        CoordinatorManager _coordinatorManager { get; set; }
        RespondentManager _respondentManager { get; set; }
        ResponseManager _responseManager { get; set; }

        public RespondentController(SurveyManager surveyManager, CoordinatorManager coordinatorManager, RespondentManager respondentManager, ResponseManager responseManager)
        {
            this._surveyManager = surveyManager;
            this._coordinatorManager = coordinatorManager;
            this._respondentManager = respondentManager;
            this._responseManager = responseManager;
        }

        /* Coordinator Respondent Page */
        public IActionResult Index()
        {
            ViewBag.Statistic1 = _surveyManager.GetAllOpenSurveys().Count;
            ViewBag.Statistic2 = joinSurveyCount().ToString();
            return View();
        }

        /* Respondent Quit */
        public IActionResult Quit()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        /* Respondent Statistics Page */
        public IActionResult Statistics()
        {
            return View();
        }

        /************************** SURVEYS OPERATIONS **************************/

        /* Open Surveys Page */
        public IActionResult OpenSurveys()
        {
            return View(_surveyManager.GetAllOpenSurveys());
        }

        public IActionResult Survey(string Id)
        {
            Respondent respondent = _respondentManager.GetByUsername(HttpContext.Session.GetString("SessionUsernameRespondent"));
            if (respondent == null)
            {
                return RedirectToAction("Error", "Home");
            }
            Survey survey = _surveyManager.GetById(Id);
            if (survey == null)
            {
                return RedirectToAction("Error", "Home");
            }
            if (_responseManager.CheckRespondentJoinThisSurvey(survey.Id, respondent.Id) == false)
            {
                ViewBag.RespondentAnswers = _responseManager.GetBySurveyAndRespondent(survey.Id, respondent.Id);
                survey.Title = "ErrorCode202akfjryhskfhfgsgsgajskkf";
            }
            return View(survey);
        }
        [HttpPost]
        public IActionResult Survey(string Id, string[] radiovalue)
        {
            Respondent respondent = _respondentManager.GetByUsername(HttpContext.Session.GetString("SessionUsernameRespondent"));
            if (respondent == null)
            {
                return RedirectToAction("Error", "Home");
            }
            Survey findSurvey = _surveyManager.GetById(Id);
            if (_responseManager.CheckRespondentJoinThisSurvey(findSurvey.Id, respondent.Id) == false)
            {
                return RedirectToAction("Error", "Home");
            }
            if (radiovalue.Length != findSurvey.Questions.Count)
            {
                return RedirectToAction("Error", "Home");
            }

            Response response = new Response();
            response.Title = findSurvey.Title;
            response.Answers = radiovalue;
            response.SurveyId = findSurvey.Id;
            response.RespondentId = respondent.Id;

            _responseManager.Add(response);

            TempData["MsgSuccess"] = "Your answers saved succesfully. Thanks for your join.";
            return RedirectToAction("OpenSurveys");
        }

        /* Open Surveys Page */
        public IActionResult JoinedSurveys()
        {
            Respondent respondent = _respondentManager.GetByUsername(HttpContext.Session.GetString("SessionUsernameRespondent"));
            if (respondent == null)
            {
                return RedirectToAction("Error", "Home");
            }
            List<Response> responses = _responseManager.GetAll().Where(x => x.RespondentId == respondent.Id).ToList();
            List<Survey> findSurveys = new List<Survey>();
            for (int i = 0; i < responses.Count; i++)
            {
                findSurveys.Add(_surveyManager.GetById(responses[i].SurveyId.ToString()));
            }
            return View(findSurveys);
        }

        int joinSurveyCount()
        {
            Respondent respondent = _respondentManager.GetByUsername(HttpContext.Session.GetString("SessionUsernameRespondent"));
            List<Response> responses = _responseManager.GetAll().Where(x => x.RespondentId == respondent.Id).ToList();
            List<Survey> findSurveys = new List<Survey>();
            for (int i = 0; i < responses.Count; i++)
            {
                findSurveys.Add(_surveyManager.GetById(responses[i].SurveyId.ToString()));
            }
            return findSurveys.Count;
        }

    }
}

AChallenge.WebUI/Views/Respondent/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutRespondent.cshtml";
}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Respondent Dashboard</h1>
    <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
</div>

<!-- Content Row -->
<div class="row">

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-6 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Open Survey</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">@ViewBag.Statistic1</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-6 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Your Survey</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">@ViewBag.Statistic2</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

AChallenge.WebUI/Views/Respondent/JoinedSurveys.cshtml
@model IEnumerable<AChallenge.Models.Concrete.Survey>
@{
    ViewData["Title"] = "JoinedSurveys";
    Layout = "~/Views/Shared/_LayoutRespondent.cshtml";
}

<div class="card">
    @if (TempData["MsgSuccess"] != null)
    {
        <div class="alert alert-success">@TempData["MsgSuccess"]</div>
    }
    <div class="card-body">
        <h3 class="text-center">Joined Surveys <span class="badge badge-pill badge-warning">@Model.Count()</span></h3>
        <hr />
        <ul class="list-group">
            <li class="list-group-item active">Surveys List - You can see all open surveys in this list.</li>
            @foreach (var item in Model)
            {
                <li class="list-group-item"><a href="/Respondent/Survey/@item.Id">@item.Title</a></li>
            }
        </ul>
    </div>
</div>

AChallenge.WebUI/Views/Respondent/OpenSurveys.cshtml
@model IEnumerable<AChallenge.Models.Concrete.Survey>
@{
    ViewData["Title"] = "OpenSurveys";
    Layout = "~/Views/Shared/_LayoutRespondent.cshtml";
}

<div class="card">
    @if(TempData["MsgSuccess"] != null)
    {
        <div class="alert alert-success">@TempData["MsgSuccess"]</div>
    }
    <div class="card-body">
        <h3 class="text-center">Open Surveys <span class="badge badge-pill badge-warning">@Model.Count()</span></h3>
        <hr />
        <ul class="list-group">
            <li class="list-group-item active">Surveys List - You can see all open surveys in this list.</li>
            @foreach (var item in Model)
            {
                <li class="list-group-item"><a href="/Respondent/Survey/@item.Id">@item.Title</a></li>
            }
        </ul>
    </div>
</div>

AChallenge.WebUI/Views/Respondent/Survey.cshtml
@model AChallenge.Models.Concrete.Survey
@{
    ViewData["Title"] = "Survey";
    Layout = "~/Views/Shared/_LayoutRespondent.cshtml";
}

@if (Model.Title != "ErrorCode202akfjryhskfhfgsgsgajskkf")
{
    <div>
        <div class="card">
            <div class="card-body">
                <h4><b>Survey Title: </b>@Model.Title</h4>
                <p>@Model.Description</p>
            </div>
        </div><br />

        <form method="post" asp-controller="Respondent" asp-action="Survey" asp-route-Id="@Model.Id">
            @{
                int questionNumber = 1;
                int questionSSS = 0;
                int optionNumber = 0;
            }
            @foreach (var item in Model.Questions)
            {
                <div class="card">
                    <div class="card-header">
                        <h6><b>Question-@questionNumber: </b>@item.Title</h6>
                    </div>
                    <div class="card-body">
                        @foreach (var option in item.Options)
                        {
                            optionNumber++;
                            <div class="form-check">

                                <input type="radio" name="radiovalue[@(questionSSS)]" id="radiovalue[@(questionSSS)]" value="@option" required />
                                <label class="form-check-label">
                                    @option
                                </label>
                            </div>

                        }
                    </div>
                </div>
                <br />
                optionNumber++;
                questionNumber++;
                questionSSS++;
            }
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <p class="text-center"><b>Note: </b>If you complete this survey now, you will not be able to participate in this survey again.</p>
                        <center><button type="submit" class="btn btn-info">Send Survey</button></center>
                    </div>
                </div>
            </div><br />
        </form>
    </div>
}
else
{
    <div class="card">
        <div class="card-body text-center">
            <h4>Note</h4>
            <hr />
            <h5>Since you have participated in this survey before, you will not view it.</h5>
            <a href="/Respondent/OpenSurveys/" class="btn btn-info">Back to menu</a>
        </div>
    </div>
    <br />
    <div class="row">
        @{ 
            int qNumber = 1;
        }
        @foreach (var q2 in Model.Questions)
        {
            <div class="col-md-6">
                <div class="card" style="margin-bottom:25px">
                    <div class="card-body">
                        <h6><b>Question-@qNumber:</b> @q2.Title</h6>
                        <hr />
                        <ul>
                            @foreach (var q2option in q2.Options)
                            {
                                <li>@q2option</li>
                            }
                        </ul>
                        <hr />
                        <p><b>Your Answer: </b> @ViewBag.RespondentAnswers.Answers[qNumber-1]</p>
                    </div>
                </div>
            </div>
            qNumber++;
        }
    </div>

}


<script src="~/vendor/jquery/jquery.min.js"></script>
<script>

</script>