AChallenge.WebUI/Controllers/CoordinatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AChallenge.Business.Concrete;
using AChallenge.Models.Concrete;
using AChallenge.QrCodeCreator;
using AChallenge.WebUI.Helpers.Auth;
using AChallenge.WebUI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AChallenge.WebUI.Controllers
{
    [AuthFilter]
    public class CoordinatorController : Controller
    {

        SurveyManager _surveyManager { get; set; }
        CoordinatorManager _coordinatorManager { get; set; }
        RespondentManager _respondentManager { get; set; }
        ResponseManager _responseManager { get; set; }

        public CoordinatorController(SurveyManager surveyManager, CoordinatorManager coordinatorManager, RespondentManager respondentManager, ResponseManager responseManager)
        {
            this._surveyManager = surveyManager;
            this._coordinatorManager = coordinatorManager;
            this._respondentManager = respondentManager;
            this._responseManager = responseManager;
        }

        /* Coordinator Dashboard Page */
        public IActionResult Index()
        {
            Coordinator coordinator = _coordinatorManager.GetByUsername(HttpContext.Session.GetString("SessionUsername"));
            if (coordinator == null)
            {
                return RedirectToAction("Error", "Home");
            }
            ViewBag.Statistic1 = _surveyManager.GetAllOpenSurveys().Count;
            ViewBag.Statistic2 = _surveyManager.GetAllByCoordinatorId(coordinator.Id).Count;
            ViewBag.Statistic3 = _responseManager.GetAll().Count;
            ViewBag.Statistic4 = _responseManager.GetAll().Count;
            return View();
        }

        /* Coordinator Quit */
        public IActionResult Quit()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index","Home");
        }

        /* Coordinator Statistics Page */
        public IActionResult Statistics()
        {
            return View();
        }

        /************************** SURVEYS OPERATIONS **************************/

        /* Coordinator Open Surveys Page */
        public IActionResult OpenSurveys()
        {
            return View(_surveyManager.GetAllOpenSurveys());
        }

        /* Coordinator Open Survey Detail Page */
        public IActionResult OpenSurvey(string Id)
        {
            Survey findSurvey = _surveyManager.GetById(Id);
            return View(findSurvey);
        }

        /* Coordinator My Surveys Page */
        public IActionResult MySurveys()
        {
            Coordinator coordinator = _coordinatorManager.GetByUsername(HttpContext.Session.GetString("SessionUsername"));
            if (coordinator == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(_surveyManager.GetAllByCoordinatorId(coordinator.Id));
        }

        /* Coordinator Add Survey Page */
        public IActionResult AddSurvey()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddSurvey(Survey survey)
        {
            Coordinator coordinator = _coordinatorManager.GetByUsername(HttpContext.Session.GetString("SessionUsername"));
            if (coordinator == null)
            {
                return RedirectToAction("Error", "Home");
            }
            List<Question> questions = new List<Question>();
            survey.CreatedDate = DateTime.Now.ToShortDateString();
            survey.IsVisible = "true";
            survey.Questions = questions;
            survey.CoordinatorId = coordinator.Id;
            _surveyManager.Add(survey);
            TempData["MsgSuccess"] = "Added a new survey to system.";
            return RedirectToAction("MySurveys");
        }

        /* Delete Survey */
        public IActionResult DeleteSurvey(string Id)
        {
            Coordinator coordinator = _coordinatorManager.GetByUsername(HttpContext.Session.GetString("SessionUsername"));
            if (coordinator == null)
            {
                return RedirectToAction("Error", "Home");
            }
            Survey findSurvey = _surveyManager.GetById(Id);
            if (findSurvey.CoordinatorId != coordinator.Id)
            {
                return RedirectToAction("Error", "Home");
            }
            _surveyManager.Delete(Id);
            TempData["MsgSuccess"] = "Survey deleted succesfully.";
            return RedirectToAction("MySurveys");
        }

        /* Survey Qr Code */
        public IActionResult SurveyQrCode(string Id)
        {
            Survey findSurvey = _surveyManager.GetById(Id);
            Byte[] testing = GenerateQrCoder.Generate(findSurvey.Id.ToString());
            return View(testing);
        }

        /* Edit Survey */
        [HttpPost]
        public IActionResult EditSurvey(string Id, string Title, string Description, string IsVisible)
        {
            Coordinator coordinator = _coordinatorManager.GetByUsername(HttpContext.Session.GetString("SessionUsername"));
            if (coordinator == null)
            {
                return RedirectToAction("Error", "Home");
            }
            Survey findSurvey = _surveyManager.GetById(Id);
            if (findSurvey.CoordinatorId != coordinator.Id)
            {
                return RedirectToAction("Error", "Home");
            }
            findSurvey.Title = Title;
            findSurvey.Description = Description;
            findSurvey.IsVisible = IsVisible;
            _surveyManager.Update(Id, findSurvey);
            TempData["MsgSuccess"] = "Survey updated succesfully.";
            return RedirectToAction("MySurveys");
        }

        /************************** QUESTION OPERATIONS **************************/

        /* This function list question of form */
        public IActionResult Questions(string Id)
        {
            Coordinator coordinator = _coordinatorManager.GetByUsername(HttpContext.Session.GetString("SessionUsername"));
            if (coordinator == null)
            {
                return RedirectToAction("Error", "Home");
            }
            Survey findSurvey = _surveyManager.GetById(Id);
            if (findSurvey.CoordinatorId != coordinator.Id)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(findSurvey);
        }

        [HttpPost]
        public IActionResult Questions(string Id, string Title,string[] fieldName)
        {
            Coordinator coordinator = _coordinatorManager.GetByUsername(HttpContext.Session.GetString("SessionUsername"));
            if (coordinator == null)
            {
                return RedirectToAction("Error", "Home");
            }
            Survey findSurvey = _surveyManager.GetById(Id);
            if (findSurvey.CoordinatorId != coordinator.Id)
            {
                return RedirectToAction("Error", "Home");
            }
            Question question = new Question();
            question.Title = Title;
            question.Options = fieldName;
            findSurvey.Questions.Add(question);
            _surveyManager.Update(Id, findSurvey);
            TempData["MsgSuccess"] = "Added a new question to survey.";
            return RedirectToAction("Questions", new { Id = findSurvey.Id });
        }

        [HttpPost]
        public IActionResult EditQuestion(string Id, string Number, string Title, string[] fieldName)
        {
            Coordinator coordinator = _coordinatorManager.GetByUsername(HttpContext.Session.GetString("SessionUsername"));
            if (coordinator == null)
            {
                return RedirectToAction("Error", "Home");
            }
            Survey findSurvey = _surveyManager.GetById(Id);
            if (findSurvey.CoordinatorId != coordinator.Id)
            {
                return RedirectToAction("Error", "Home");
            }
            Question question = new Question();
            question.Title = Title;
            question.Options = fieldName;
            findSurvey.Questions[Convert.ToInt16(Number) - 1] = question;
            _surveyManager.Update(Id, findSurvey);
            TempData["MsgSuccess"] = "Updated a new question to survey.";
            return RedirectToAction("Questions", new { Id = findSurvey.Id });
        }

        [HttpPost]
        public IActionResult DeleteQuestion(string Id, string Number)
        {
            Coordinator coordinator = _coordinatorManager.GetByUsername(HttpContext.Session.GetString("SessionUsername"));
            if (coordinator == null)
            {
                return RedirectToAction("Error", "Home");
            }
            Survey findSurvey = _surveyManager.GetById(Id);
            if (findSurvey.CoordinatorId != coordinator.Id)
            {
                return RedirectToAction("Error", "Home");
            }
            findSurvey.Questions.RemoveAt(Convert.ToInt16(Number) - 1);
            _surveyManager.Update(Id, findSurvey);
            TempData["MsgSuccess"] = "Deleted a question to survey.";
            return RedirectToAction("Questions", new { Id = findSurvey.Id });
        }

        /************************** RESPONSE OPERATIONS **************************/

        /* Show responses by survey id */
        public IActionResult Responses(string Id)
        {
            Coordinator coordinator = _coordinatorManager.GetByUsername(HttpContext.Session.GetString("SessionUsername"));
            if (coordinator == null)
            {
                return RedirectToAction("Error", "Home");
            }
            Survey findSurvey = _surveyManager.GetById(Id);
            if (findSurvey.CoordinatorId != coordinator.Id)
            {
                return RedirectToAction("Error", "Home");
            }
            ViewBag.SurveyName = findSurvey.Title;

AChallenge.WebUI/Views/Coordinator/AddSurvey.cshtml
@model AChallenge.Models.Concrete.Survey
@{
    ViewData["Title"] = "AddSurvey";
    Layout = "~/Views/Shared/_LayoutCoordinator.cshtml";
}

<form method="post" asp-controller="Coordinator" asp-action="AddSurvey">
    <div class="card border-left-primary">
        <div class="card-body">
            <h3 class="text-center">Add a new survey</h3>
            <hr />
            <div class="form-group col-md-8 offset-md-2">
                <label>Survey Title</label>
                <input asp-for="Title" type="text" class="form-control" required />
            </div>
            <div class="form-group col-md-8 offset-md-2">
                <label>Survey Description</label>
                <input asp-for="Description" type="text" class="form-control" required />
            </div>
            <div class="form-group col-md-12">
                <center><button type="submit" class="btn btn-info">Create Survey</button></center>
            </div>
        </div>
    </div>
    <br />
</form>

AChallenge.WebUI/Views/Coordinator/MySurveys.cshtml
@model IEnumerable<AChallenge.Models.Concrete.Survey>
@{
    ViewData["Title"] = "MySurveys";
    Layout = "~/Views/Shared/_LayoutCoordinator.cshtml";
}

<h2 class="text-center">My Surveys</h2>
<a href="/Coordinator/AddSurvey/" class="btn btn-info">Create a new survey</a>
<hr />

<div class="card">
    <div class="card-body">
        @if (TempData["MsgSuccess"] != null)
        {
            <div class="alert alert-success">@TempData["MsgSuccess"]</div>
        }
        @if (Model.Count() > 0)
        {
            <div class="table-responsive">
                <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                    <thead>
                        <tr role="row">
                            <th>Id</th>
                            <th>Created Date</th>
                            <th>Is Visible</th>
                            <th>Responses</th>
                            <th>Operations</th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        @foreach (var item in Model)
                        {
                            var tm = "#ModalEdit" + item.Id;
                            var mid = "ModalEdit" + item.Id;

                            <tr role="row" class="odd">
                                <td>@item.Id</td>
                                <td>@item.CreatedDate</td>
                                <td>@item.IsVisible</td>
                                <td>
                                    <a href="/Coordinator/Responses/@item.Id" class="btn btn-success btn-sm">Show Responses</a>
                                </td>
                                <td style="width:25%">
                                    <a href="/Coordinator/Questions/@item.Id" class="btn btn-info btn-sm">Edit Questions</a>
                                    <a href="" data-target="@tm" data-toggle="modal" data-target="#ModalEdit" class="btn btn-warning btn-sm">Edit Survey</a>
                                </td>
                            </tr>

                            <!-- Edit Modal -->
                            <div id="@mid" class="modal" tabindex="-1" role="dialog">
                                <div class="modal-dialog" role="document">
                                    <form method="post" asp-controller="Coordinator" asp-action="EditSurvey" asp-route-Id="@item.Id">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title">Edit Survey <small><a href="/Coordinator/DeleteSurvey/@item.Id" class="btn btn-danger btn-sm">Delete</a></small></h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <div class="form-group">
                                                    <label>Title</label>
                                                    <input id="Title" name="Title" class="form-control" type="text" value="@item.Title" />
                                                </div>
                                                <div class="form-group">
                                                    <label>Description</label>
                                                    <input id="Description" name="Description" class="form-control" type="text" value="@item.Description" />
                                                </div>
                                                <div class="form-group">
                                                    <label>Is Visible</label>
                                                    <select id="IsVisible" name="IsVisible" class="form-control">
                                                        <option>@item.IsVisible</option>
                                                        <option>true</option>
                                                        <option>false</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-primary">Edit Survey</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                        }
                    </tbody>
                </table>
            </div>
        }
        else
        {
            <h4 class="text-center">You didn't add a survey yet</h4>
        }
    </div>
</div>

<script src="~/vendor/jquery/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('#dataTable').DataTable();
    });
</script>

AChallenge.WebUI/Views/Coordinator/OpenSurvey.cshtml
@model AChallenge.Models.Concrete.Survey
@{
    ViewData["Title"] = "OpenSurvey";
    Layout = "~/Views/Shared/_LayoutCoordinator.cshtml";
}

<div class="card">
    <div class="card-body text-center">
        <h4>@Model.Title</h4>
        <a href="/Coordinator/SurveyQrCode/@Model.Id" class="btn btn-info btn-sm" target="_blank">Show Survey QR Code</a>
        <hr />
    </div>
</div>
<br />
<div class="row">
    @{
        int qNumber = 1;
    }
    @foreach (var q2 in Model.Questions)
    {
        <div class="col-md-6">
            <div class="card" style="margin-bottom:25px">
                <div class="card-body">
                    <h6><b>Question-@qNumber:</b> @q2.Title</h6>
                    <hr />
                    <ul>
                        @foreach (var q2option in q2.Options)
                        {
                            <li>@q2option</li>
                        }
                    </ul>
                </div>
            </div>
        </div>
        qNumber++;
    }
</div>

AChallenge.WebUI/Views/Coordinator/Questions.cshtml
@model AChallenge.Models.Concrete.Survey
@{
    ViewData["Title"] = "Questions";
    Layout = "~/Views/Shared/_LayoutCoordinator.cshtml";
}

<div class="card text-center border-left-primary">
    <div class="card-body">
        <h3>@Model.Title</h3>
        <p>@Model.Description</p>
    </div>
</div>
<br />
<div class="card text-center border-left-primary">
    <div class="card-body">
        @if (TempData["MsgSuccess"] != null)
        {
            <div class="alert alert-success">@TempData["MsgSuccess"]</div>
        }
        <h3>Questions</h3>
        <a href="" data-toggle="modal" data-target="#ModalAdd" class="btn btn-info">Add a new question</a><br /><br />

        <div class="accordion col-md-10 offset-md-1" id="accordionExample">

            @{
                int questionNumber = 0;
                int questionNumberForTitle = 1;
            }
            @foreach (var item in Model.Questions)
            {
                var tm = "#ModalEdit" + questionNumber;
                var mid = "ModalEdit" + questionNumber;

                var tm2 = "#ModalDelete" + questionNumber;
                var mid2 = "ModalDelete" + questionNumber;

                <!-- each question -->
                <div class="card text-left">
                    <div class="card-header" id="headingOne">
                        <h2 class="mb-0">
                            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse-@questionNumber" aria-expanded="true" aria-controls="collapseOne">
                                Question-@questionNumberForTitle: @item.Title
                            </button>
                        </h2>
                    </div>
                    <div id="collapse-@questionNumber" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                        <div class="card-body">
                            <ul>
                                @foreach (var option in item.Options)
                                {
                                    <li>@option</li>
                                }
                            </ul>
                            <row>
                                <a href="" data-target="@tm" data-toggle="modal" data-target="#ModalEdit" class="btn btn-info">Update</a>
                                <a href="" data-target="@tm2" data-toggle="modal" data-target="#ModalDelete" class="btn btn-danger">Delete</a>
                            </row>
                        </div>
                    </div>
                </div>
                questionNumber++;
                questionNumberForTitle++;

                <!-- Edit Modal -->
                <div id="@mid" class="modal" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                        <form method="post" asp-controller="Coordinator" asp-action="EditQuestion" asp-route-Id="@Model.Id">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Edit Question</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <div class="form-group" style="display:none">
                                        <label>Question Number</label>
                                        <input id="Number" name="Number" type="text" class="form-control" value="@questionNumber" required />
                                    </div>
                                    <div class="form-group">
                                        <label>Question Title</label>
                                        <input id="Title" name="Title" type="text" class="form-control" value="@item.Title" required />
                                    </div>
                                    <div class="form-group">
                                        <label>Old Questions</label>
                                        <ul>
                                            @foreach (var oldQuestion in item.Options)
                                            {
                                                <li>@oldQuestion</li>
                                            }
                                        </ul>

                                    </div>
                                    <p>Update Questions</p>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div data-role="dynamic-fields">
                                                <div class="form-inline">
                                                    <div class="form-group">
                                                        <label class="sr-only" for="field-name">Option Name</label>
                                                        <input type="text" class="form-control" id="fieldName" name="fieldName" placeholder="Option Name" required>
                                                    </div>
                                                    <button class="btn btn-danger" data-role="remove">
                                                        <span class="fa fa-trash"></span>
                                                    </button>
                                                    <button class="btn btn-primary" data-role="add">
                                                        <span class="fa fa-plus"></span>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <button type="submit" class="btn btn-primary">Edit Question</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <!-- Delete Modal -->
                <div id="@mid2" class="modal" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                        <form method="post" asp-controller="Coordinator" asp-action="DeleteQuestion" asp-route-Id="@Model.Id">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Delete Question</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <div class="form-group" style="display:none">
                                        <label>Question Number</label>
                                        <input id="Number" name="Number" type="text" class="form-control" value="@questionNumber" required />
                                    </div>
                                    <p>
                                        Do you want to delete this question?
                                    </p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <button type="submit" class="btn btn-danger">Delete Question</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            }

        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="ModalAdd" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="post" asp-controller="Coordinator" asp-action="Questions" asp-route-Id="@Model.Id">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add a new question</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <div class="form-group">
                        <label>Question Title</label>
                        <input id="Title" name="Title" type="text" class="form-control" required />
                    </div>
                    <p>Questions</p>
                    <div class="row">
                        <div class="col-md-12">
                            <div data-role="dynamic-fields">
                                <div class="form-inline">
                                    <div class="form-group">
                                        <label class="sr-only" for="field-name">Option Name</label>
                                        <input type="text" class="form-control" id="fieldName" name="fieldName" placeholder="Option Name" required>
                                    </div>
                                    <button class="btn btn-danger" data-role="remove">
                                        <span class="fa fa-trash"></span>
                                    </button>
                                    <button class="btn btn-primary" data-role="add">
                                        <span class="fa fa-plus"></span>
                                    </button>
                                </div>  <!-- /div.form-inline -->
                            </div>  <!-- /div[data-role="dynamic-fields"] -->
                        </div>  <!-- /div.col-md-12 -->
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Add Question</button>
                </div>
            </form>
        </div>

    </div>
</div>

<style>
    [data-role="dynamic-fields"] > .form-inline + .form-inline {
        margin-top: 0.5em;
    }

    [data-role="dynamic-fields"] > .form-inline [data-role="add"] {
        display: none;
    }

    [data-role="dynamic-fields"] > .form-inline:last-child [data-role="add"] {
        display: inline-block;
    }

    [data-role="dynamic-fields"] > .form-inline:last-child [data-role="remove"] {
        display: none;
    }
</style>
<script src="~/vendor/jquery/jquery.min.js"></script>
<script>
    $(function () {
        // Remove button click
        $(document).on(
            'click',
            '[data-role="dynamic-fields"] > .form-inline [data-role="remove"]',
            function (e) {
                e.preventDefault();
                $(this).closest('.form-inline').remove();
            }
        );
        // Add button click
        $(document).on(
            'click',
            '[data-role="dynamic-fields"] > .form-inline [data-role="add"]',
            function (e) {
                e.preventDefault();
                var container = $(this).closest('[data-role="dynamic-fields"]');
                new_field_group = container.children().filter('.form-inline:first-child').clone();
                new_field_group.find('input').each(function () {
                    $(this).val('');
                });
                container.append(new_field_group);
            }
        );
    });


</script>

AChallenge.WebUI/Views/Coordinator/ResponseDetail.cshtml
@model AChallenge.Models.Concrete.Response
@{
    ViewData["Title"] = "ResponseDetail";
    Layout = "~/Views/Shared/_LayoutCoordinator.cshtml";
}

<div class="card">
    <div class="card-body text-center">
        <h4>Response Detail</h4>
        <hr />
        <h5>@ViewBag.FindSurveyTitle</h5>
    </div>
</div>
<br />
<div class="row">
    @{
        int qNumber = 1;
    }
    @foreach (var item in Model.Answers)
    {
    <div class="col-md-6">
        <div class="card" style="margin-bottom:25px">
            <div class="card-body">
                <h6><b>Question-@qNumber:</b> @ViewBag.FindSurvey[qNumber-1].Title</h6>
                <hr />
                <ul>
                    @foreach (var qOption in @ViewBag.FindSurvey[qNumber - 1].Options)
                    {
                        if (qOption == item)
                        {
                            <li><b>@qOption</b></li>
                        }
                        else
                        {
                            <li>@qOption</li>
                        }
                    }
                </ul>
                <hr />
            <p><b>Respondent Answer: </b> @item</p>
        </div>
    </div>
    </div>
        qNumber++;
    }
</div>

AChallenge.WebUI/Views/Coordinator/Statistics.cshtml
@model AChallenge.WebUI.Models.CoordinatorStatsViewModel
@{
    ViewData["Title"] = "Statistics";
    Layout = "~/Views/Shared/_LayoutCoordinator.cshtml";
}



<script src="~/vendor/jquery/jquery.min.js"></script>